Repository JeffersonLab/hps-java, pull requests merged in 2020-03, with the labels that each got.

#673 Iss666
  ecal-recon/src/main/java/org/hps/recon/ecal/HodoRawConverterDriver.java
Labels: cleanup

#680 Update PhysicsRun2016FullReconMC.lcsim
  steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2016FullReconMC.lcsim
Labels: minor

#685 Iss677 - Layer 0/1 changes and 2019 trigger drivers
  detector-data/detectors/HPS-PhysicsRun2019-v1-4pt5/.HPS-PhysicsRun2019-v1-4pt5.lcdd.swp
  detector-model/src/main/java/org/lcsim/detector/tracker/silicon/HpsThinSiSensor.java
  detector-model/src/main/java/org/lcsim/detector/tracker/silicon/SiStriplets.java
  ecal-readout-sim/src/main/java/org/hps/readout/DigitizationReadoutDriver.java
  ecal-readout-sim/src/main/java/org/hps/readout/RawConverterReadoutDriver.java
  ecal-readout-sim/src/main/java/org/hps/readout/hodoscope/HodoscopeDigitizationReadoutDriver.java
  ecal-readout-sim/src/main/java/org/hps/readout/hodoscope/HodoscopePatternReadoutDriver.java
  ecal-readout-sim/src/main/java/org/hps/readout/rawconverter/AbstractBaseRawConverter.java
  ecal-readout-sim/src/main/java/org/hps/readout/trigger2019/PairsTrigger2019ReadoutDriver.java
  ecal-readout-sim/src/main/java/org/hps/readout/trigger2019/SinglesTrigger2019ReadoutDriver.java
  record-util/src/main/java/org/hps/readout/util/HodoscopePattern.java
  record-util/src/main/java/org/hps/record/triggerbank/TriggerModule2019.java
  steering-files/src/main/resources/org/hps/steering/readout/PhysicsRun2019TrigPairs.lcsim
  steering-files/src/main/resources/org/hps/steering/readout/PhysicsRun2019TrigPulse.lcsim
  steering-files/src/main/resources/org/hps/steering/readout/PhysicsRun2019TrigSingles.lcsim
  steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2019MCRecon.lcsim
  steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2019Recon.lcsim
  tracking/src/main/java/org/hps/recon/tracking/DefaultSiliconResolutionModel.java
  tracking/src/main/java/org/hps/recon/tracking/HelicalTrackHitDriver.java
  tracking/src/main/java/org/hps/recon/tracking/SiTrackerHitStrip1D.java
  tracking/src/main/java/org/hps/recon/tracking/StripMaker.java
  tracking/src/main/java/org/hps/recon/tracking/gbl/MakeGblTracks.java
  tracking/src/main/java/org/hps/recon/tracking/kalman/KalmanInterface.java
  tracking/src/main/java/org/hps/recon/tracking/kalman/KalmanPatRecDriver.java
  tracking/src/main/java/org/hps/recon/tracking/kalman/KalmanPatRecHPS.java
Labels: critical, enhancement
