Repository JeffersonLab/hps-java, pull requests merged in 2021-05, with the labels that each got.

#856 Update PhysicsRun2019_pass0_recon.lcsim
  steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2019_pass0_recon.lcsim
Labels: enhancement

#854 Correct phi0 due to expected output range from HTF
  tracking/src/main/java/org/hps/recon/tracking/gbl/FittedGblTrajectory.java
Labels: bug

#863 HPS detector for running at 1.92 GeV
  detector-data/detectors/HPS-v2021-1pt92GeV/HPS-v2021-1pt92GeV.lcdd
  detector-data/detectors/HPS-v2021-1pt92GeV/SamplingFractions/Ecal.properties
  detector-data/detectors/HPS-v2021-1pt92GeV/SamplingFractions/Hodoscope.properties
  detector-data/detectors/HPS-v2021-1pt92GeV/compact.xml
  detector-data/detectors/HPS-v2021-1pt92GeV/detector.properties
Labels: New Detector

#865 Iss864
  recon/src/main/java/org/hps/recon/particle/HpsReconParticleDriver.java
  recon/src/main/java/org/hps/recon/particle/ReconParticleDriver.java
  steering-files/src/main/resources/org/hps/steering/recon/PhysicsRun2019_pass0_KFOnly.lcsim
Labels: enhancement
